version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST: postgres
    ports:
      - 5430:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6389:6379
    volumes:
      - redis_data:/data

  app:
    build: .
    restart: always
    ports:
      - 4000:4000
    environment:
      DB_URL: postgresql://postgres:1234@postgres:5432/postgres
      ACCESS_TOKEN_KEY: sf45brh7dfg5w
      ACCESS_TOKEN_EXP: 1d
      REFRESH_TOKEN_KEY: usm12123n21!@3423
      REFRESH_TOKEN_EXP: 7d
      TOKEN_KEY: asu923b81212381bwb
      COOKIE_EXP: 7*24*3600000
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis

volumes:
  db_data:
  redis_data:
